[tool.poetry]
name = "mrfmsim-plot"
version = "0.1.1"
description = "Plotting functions for magnetic resonance force microscopy experiments"
authors = ["Peter Sun <hs859@cornell.edu>"]
maintainers = ["Peter Sun <hs859@cornell.edu>"]
repository = "https://www.github.edu/Marohn-Group/mrfmsim-plot"
readme = "README.rst"
packages = [
    { include = "mrfmsim_plot/*.py" }
]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "==1.26.4"
pyvista = "==0.44.2"
vtk = { version = "==9.3.1", optional = true }
mayavi = { version = "==4.8.2", optional = true }
pyqt5 = { version = "==5.15.11", optional = true }
pytest = { version = ">=7.1.1", optional = true }
pytest-cov = { version = ">=3.0.0", optional = true }


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
pytest = ">=7.1.1"
pytest-cov = ">=3.0.0"

[tool.poetry.extras]
test = ["pytest", "pytest-cov"]
mayavi = ["mayavi", "vtk", "pyqt5"]

[tool.pytest.ini_options]
filterwarnings = [
    # the plot plugin's mayavi package has a deprecation warning
    'ignore::DeprecationWarning',
]

[tool.coverage.run]
# pytest coverage
source_pkgs = [
    'mrfmsim_plot',
]
omit = ['tests/*']
