import numpy as np
from mayavi import mlab


def image_plane(dataset, grid, colormap=None, *args, **kwargs):
    """Plot the data in the grid with sliding planes widgets in x, y, z
    direction

    The x, y, z grid used needs to be full-sized grid, meaning x, y, z and
    dataset have the same dimensions and shape.

    :param np.array/list grid_array: full grid in x,y,z direction
        This can be generated by np.mgrid, or np.broadcast_arrays of
        appropriate shape. For mrfmsim, use ``grid.full_array``.
    :param np.array dataset: data to image
    :param string title: the title of the image

    :raises AssertionError: if the shape of grid_array and
        dataset are not equal
    """

    extent = grid.grid_extents(grid.grid_range, grid.grid_origin).ravel()
    grid_array_full = np.broadcast_arrays(*grid.grid_array)

    mlab.figure(size=(600, 600))
    vtk_dataset = mlab.pipeline.scalar_field(*grid_array_full, dataset)
    for i, orientation in enumerate(["x_axes", "y_axes", "z_axes"]):
        mlab.pipeline.image_plane_widget(
            vtk_dataset,
            plane_orientation=orientation,
            slice_index=grid.grid_shape[i] / 2,
            colormap=colormap or "jet",
        )
    mlab.outline()
    mlab.axes(extent=extent)
    mlab.colorbar(orientation="vertical")

    return mlab
